### ISSUE TITLE
`FileSpec` as parameter should be a `Mapping`, not a `dict`, to avoid variance issues

### ISSUE THREAD

**Issue by Avasam** [jaraco/jaraco.path#6]
See https://github.com/pypa/setuptools/pull/4599/files#diff-19b6ed43e0708223cda0de9aed6071f1e0f04aab82e6610ba23e7257326f2a04R186 for an example where it causes issues

**Comment by jaraco** [comment]
`FileSpec` isn't part of this library, but the confusion is understandable. This project is `path`, but `FileSpec` is found in [`jaraco.path`](/jaraco/jaraco.path).

**Comment by jaraco** [comment]
This was fixed in #3 and released in v3.7.2 (which just made it to PyPI today due to #5).
